# pH Recognition using RGB Color. 

In [38]:
#importing the packages.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import colorsys

In [39]:
#reading the dataset.
ds = pd.read_csv('ph-data.csv')
ds

blue  green  red  label
0      36     27  231      0
1      36     84  250      1
2      37    164  255      2
3      22    205  255      3
4      38    223  221      4
..    ...    ...  ...    ...
737   188    196   16      9
738   216    156   76     10
739   212    148   80     10
740   172     84   64     11
741   172     84   96     12

[742 rows x 4 columns]

In [40]:
ds[["blue", "green", "red"]] = ds[["blue", "green", "red"]] / 255

In [41]:
ds[["red","green", "blue" ]] = ds[["red","green", "blue" ]].apply(lambda x: pd.Series(colorsys.rgb_to_hsv(*x), index=['red', 'green', 'blue']), axis=1)

In [42]:
ds

blue     green       red  label
0    0.905882  0.883117  0.992647      0
1    0.980392  0.856000  0.037383      1
2    1.000000  0.854902  0.097095      2
3    1.000000  0.913725  0.130901      3
4    0.874510  0.829596  0.168468      4
..        ...       ...       ...    ...
737  0.768627  0.918367  0.492593      9
738  0.847059  0.648148  0.571429     10
739  0.831373  0.622642  0.580808     10
740  0.674510  0.627907  0.635802     11
741  0.674510  0.511628  0.689394     12

[742 rows x 4 columns]

In [34]:
colorsys.rgb_to_hsv(231/255,27/255, 36/255)

(0.9926470588235294, 0.8831168831168832, 0.9058823529411765)

In [ ]:
ds["blue"].corr(ds["label"])

In [ ]:
ds["red"].corr(ds["label"])

In [ ]:
ds["green"].corr(ds["label"])

In [5]:
ds = ds[["red", "blue", "label"]]
ds

red      blue  label
0    0.992647  0.905882      0
1    0.037383  0.980392      1
2    0.097095  1.000000      2
3    0.130901  1.000000      3
4    0.168468  0.874510      4
..        ...       ...    ...
648  0.564677  0.788235     10
649  0.661359  0.796078     11
650  0.647383  0.662745     12
651  0.718137  0.678431     13
652  0.763566  0.513725     14

[653 rows x 3 columns]

In [ ]:
#dataset is consistent. 
ds_plot = ds.label.value_counts()
ds_plot.plot(kind = 'bar')
plt.xticks(rotation=45)
plt.xlabel('pH Scale')
plt.ylabel('Count')
plt.savefig("count_plot.png", dpi = 1000, transparent = True)

In [31]:
X = ds.iloc[:, :-1].columns
X
# y = ds.iloc[:, -1].columns

Index(['blue', 'green', 'red'], dtype='object')

In [43]:
#selecting X and y for classification.
X = ds.iloc[:, :-1].values
y = ds.iloc[:, -1].values

In [25]:
print(X)

[[0.91 0.88 0.99]
 [0.98 0.86 0.04]
 [1.   0.85 0.1 ]
 ...
 [0.66 0.72 0.65]
 [0.68 0.79 0.72]
 [0.51 0.98 0.76]]


In [44]:
#reshaping y for regression.
y = y.reshape(len(y),1)
print(y)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2

In [45]:
#scaling the independent variable.
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [14]:
print(X)

[[ 0.87521907  0.32902404  2.06118638]
 [ 1.35465935  0.15836282 -1.43351586]
 [ 1.48082785  0.15145226 -1.21506905]
 ...
 [-0.68927028 -0.72288193  0.79808476]
 [-0.58833548 -0.28138474  1.05692981]
 [-1.64815085  0.96854817  1.22312427]]


In [15]:
print(y)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2

In [46]:
#splitting the dataset into test and training.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [47]:
#importing the packages.
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

SEED = 1

#variable initiation.
rf = RandomForestRegressor(random_state = SEED)
dt = DecisionTreeRegressor(random_state = 0)
svr = SVR(kernel = 'rbf')
ridge = Ridge(alpha=0.1, normalize=True)
lr = LinearRegression()

#storing in an array.
regressors = [('Multiple Linear Regression', lr),
              ('Ridge Regression', ridge),
              ('SVM', svr),
              ('Decision Tree', dt),
              ('Random Forest', rf)]

In [48]:
for reg_name, reg in regressors:
    
    #fit the model.
    reg.fit(X_train, y_train)
    
    #predicting test set results.
    y_pred = reg.predict(X_test)
    
    #reshaping into former form.
    np.set_printoptions(precision=2)
    np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)
    
    #printing r2_score.
    print('{:s} : {:f}'.format(reg_name, r2_score(y_test, y_pred)))

Multiple Linear Regression : 0.558000
Ridge Regression : 0.554113
SVM : 0.902776
Decision Tree : 0.935763


c:\Python38\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\juanm\AppData\Local\Temp\ipykernel_10988\1848948982.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  reg.fit(X_train, y_train)


Random Forest : 0.952574


In [49]:
from sklearn.externals import joblib
joblib.dump(rf, 'model.pkl')

['model.pkl']